### ISSUE TITLE
缺少typescript 类型声明

### ISSUE THREAD

**Issue by dmyz** [335296558/vite-plugin-svgs-icons#8]
无法找到模块“vite-plugin-vue-svg-icons”的声明文件。“E:/workspace/base/base-admin/node_modules/.pnpm/registry.npmmirror.com+vite-plugin-vue-svg-icons@3.1.4/node_modules/vite-plugin-vue-svg-icons/dist/index.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/vite-plugin-vue-svg-icons` (如果存在)，或者添加一个包含 `declare module 'vite-plugin-vue-svg-icons';` 的新声明(.d.ts)文件ts(7016)

**Comment by 335296558** [comment]
> 无法找到模块“vite-plugin-vue-svg-icons”的声明文件。“E:/workspace/base/base-admin/node_modules/.pnpm/registry.npmmirror.com+vite-plugin-vue-svg-icons @3.1.4/node_modules/vite-plugin-vue-svg-icons/dist/index.js”隐式式拥有“any”类型。 尝试使用`npm i --save-dev @types/vite-plugin-vue-svg-icons`（如果存在），或者添加一个包含`declare module 'vite-plugin-vue-svg-icons';`的新声明(.d.ts )文件ts(7016)

你可以先在你的目录下的 xxx.d.ts 文件中，添加 declare module 'vite-plugin-vue-svg-icons';
**后续有内容更新了会顺带支持ts的声明文件**
